-- AUTOGENERATED by build.ps1 -- DO NOT EDIT. Edit files in src/ and rebuild.
local __modules, __loaded = {}, {}
local function require(name)
  if __loaded[name] == nil then __loaded[name] = __modules[name]() end
  return __loaded[name]
end
__modules["content.floor1"] = function()
-- ===========================================================================
-- content/floor1.lua -- the dungeon floor: cell -> hall
-- ===========================================================================
-- A content module is just data + a few closures. It pulls the engine api and
-- calls the authoring helpers. Registration mutates the engine's tables, so
-- this module has nothing useful to return -- we `return true` so the require
-- shim caches it.
local g = require("engine")

-- the player avatar; carried items have location = "player"
g.register("player", { name = "you", verbs = {} }, "cell", {})

g.room {
   id = "cell",
   desc = "A damp stone cell. A heavy door is set in the north wall. A small, barred window allows a meager bit of light to shine into the cell.",
   exits = {},                  -- north appears only once the door is opened
}
g.room {
   id = "hall",
   desc = "A torchlit hall. A spiral stair winds upward; a low door leads back down.",
   exits = { south = "cell", up = "landing" },
}

g.item {
   id = "key", name = "key", location = "bread",   -- baked in the bread
   desc = "A small iron key, cold to the touch.",
}

g.door {
   id = "celldoor", name = "door", location = "cell",
   leads = { dir = "north", to = "hall", from = "cell" },
   -- key defaults to the item proto "key"
}

g.window {
   id = "cellwindow", name = "window", location = "cell",
   barred = true,                            -- permanent scenery: no key opens it, it never opens
   overlooks = "void",                       -- you can still SEE through the bars (see void's glimpse)
   -- The window is barred. react[verb] fires when the window is the TARGET of a
   -- verb -- e.g. "push key through window" or "throw key at window" (push/shove
   -- are parsed as throw). self = the window, projectile = the thing pushed.
   -- Small items slip between the bars and fall into the void, unrecoverable.
   react = {
      throw = function(self, projectile)
         projectile.location = "void"          -- the void is a fatal drop; nothing comes back
         pc.print("You slip the " .. g.P(projectile).name ..
                  " between the bars. It tumbles away into the dark below, gone for good.")
      end,
   },
}

g.room {
   id = "void",
   desc = "Beyond the bars is only open air -- a sheer drop down the tower's outer wall to the courtyard stones far, far below.",
   -- the short version shown when peering through the cell window (see g.window overlooks)
   glimpse = "open air, and a sheer drop down the tower wall to the courtyard far below.",
   -- entering this room ends the game (see the `lose` handling in engine go()).
   lose = "*** You squeeze past the bars and plummet from the tower. YOU DIED ***",
   exits = {},
}

g.item {
   id = "bread", name = "bread", location = "cell",
   state = { is_open = false},
   desc = function(e)
      if e.is_open then return "A hard crust of stale bread, torn open." end
      return "A hard and oddly heavy crust of stale bread." end,
   verbs = {
      open = function(self)
         self.is_open = true
         if #g.contents(self.id) > 0 then
            pc.print("You tear the bread open revealing a key! Weird.")
         else
            pc.print("You continue to tear into the bread. Alas, there is nothing left to find.")
         end
      end,
      eat = function(self)
         if #g.contents(self.id) > 0 then
            pc.print("You bite the hard loaf, but something even harder is inside.")
            return
         end
         self.location = nil                  -- consumed -> in no container -> gone
         pc.print("You choke down the bread. It was less than satisfying.")
      end,
   },
}

g.npc {
   id = "prisoner", name = "prisoner", location = "hall",
   desc = "A gaunt fellow prisoner slumped against the wall.",
   -- react[verb] fires when the prisoner is the TARGET of a verb ("... at/to prisoner").
   -- self = the prisoner, projectile = the thing thrown.
   react = {
      throw = function(self, projectile)
         projectile.location = g.here()      -- it bounces off and lands at your feet
         pc.print('The prisoner flinches and swats it away. "Oi! Throw that at the goblin, not me!"')
      end,
   },
   dialog = {
      start = {
         text = "You got out of your cell? That goblin on the stair won't let anyone past, though.",
         options = {
            { label = "How do I get past it?", next = "hint",
              effect = function() g.flags().knows_hint = true end },
            { label = "I'll manage." },        -- no goto -> ends the chat
         },
      },
      hint = {
         text = "That brute would chase a scrap of food off a cliff. Drop it something to eat and slip by.",
         options = { { label = "Thanks." } },
      },
   },
}

g.enemy {
   id = "goblin", name = "goblin", location = "hall",
   desc = "A wiry goblin crouches on the bottom stair, blocking the way up.",
   guarding = "up",
   tick = function(e)
      local bread = g.E("bread")
      if e.guarding and bread and bread.location == e.location then
         e.guarding = nil
         pc.print("")
         pc.print("The goblin lunges for the bread and drags it into the dark. The stair is clear!")
      end
   end,
}

return true
end
__modules["content.floor2"] = function()
-- ===========================================================================
-- content/floor2.lua -- the upper floor: landing -> study -> roof
-- ===========================================================================
-- Multi-step puzzle showcase:
--   read the book      -> learn the combination (a flag)
--   unlock the strongbox (gated by that flag, NOT by a key item)
--   open it, take the roof key
--   unlock + open the trapdoor with the roof key
--   go up -> the roof -> win
local g = require("engine")

g.room {
   id = "landing",
   desc = "A drafty landing at the top of the stair. A trapdoor is set in the ceiling.",
   exits = { down = "hall", west = "study" },   -- "up" appears when the trapdoor opens
}
g.room {
   id = "study",
   desc = "A cramped study, every shelf stripped bare but one. A strongbox sits in the corner.",
   exits = { east = "landing" },
}
g.room {
   id = "roof",
   desc = "You haul yourself onto the windswept roof. The drawbridge is far below -- but you are OUT.",
   win = true,
}

g.item {
   id = "book", name = "book", location = "study",
   desc = "A warden's ledger. One page is dog-eared.",
   verbs = {
      read = function(e)
         g.flags().knows_code = true
         pc.print('The dog-eared page reads: "Strongbox latch -- press 3, 1, 7."')
      end,
   },
}

-- a container locked by KNOWLEDGE, not a key: its custom unlock checks a flag
g.container {
   id = "strongbox", name = "strongbox", location = "study", locked = true,
   desc = function(e)
      if e.is_open then return "An open strongbox."
      elseif e.locked then return "A strongbox with a 3-digit latch."
      else return "A strongbox, latch released but lid shut." end
   end,
   verbs = {
      unlock = function(e)
         if not e.locked then
            pc.print("The latch is already released.")
         elseif g.flags().knows_code then
            e.locked = false
            pc.print("You press 3, 1, 7. The latch springs open.")
         else
            pc.print("There's a 3-digit latch. You don't know the combination.")
         end
      end,
   },
}

g.item {
   id = "roofkey", name = "roofkey", location = "strongbox",
   desc = "A heavy brass key stamped with a sun -- the roof key.",
}

g.door {
   id = "trapdoor", name = "trapdoor", location = "landing",
   key = "roofkey",                                  -- opened by the roof key, not the iron key
   leads = { dir = "up", to = "roof", from = "landing" },
}

return true
end
__modules["engine"] = function()
-- ===========================================================================
-- engine.lua -- the Escape the Tower engine + authoring helpers
-- ===========================================================================
-- This module is `require`d once. It returns an api table `M` that content
-- modules use to register rooms/items/etc., and that main.lua uses to run().
--
-- LUA REMINDER: a "module" here is just a chunk that builds a table `M` and
-- ends with `return M`. The build wraps each file's body in a function, so
-- everything below is local to THIS module -- no globals leak out.
-- ===========================================================================

local M = {}                      -- the api we hand back at the bottom
local sfx = require("sound")      -- action stingers (2-3 tone cues)

-- ---------------------------------------------------------------------------
-- 1. WORD TABLES (typed word -> canonical word; membership is an O(1) lookup)
-- ---------------------------------------------------------------------------
local move_verbs = {
   go = true, move = true, walk = true, run = true, climb = true, head = true,
}
local dir_canon = {               -- direction synonym -> canonical direction
   north = "north", n = "north",
   south = "south", s = "south",
   west  = "west",  w = "west",
   east  = "east",  e = "east",
   up = "up", u = "up", rise = "up", ascend = "up",
   down = "down", d = "down", descend = "down",
}
local verb_canon = {              -- action synonym -> canonical verb
   look = "look", examine = "look", inspect = "look",
   take = "take", get = "take", grab = "take", pick = "take",
   drop = "drop",
   throw = "throw", toss = "throw", chuck = "throw",
   push = "throw", shove = "throw", slip = "throw",   -- push/shove route through the same handler as throw
   open = "open", close = "close", shut = "close",
   unlock = "unlock", lock = "lock",
   eat = "eat", drink = "eat",
   talk = "talk", speak = "talk", ask = "talk",
   attack = "attack", hit = "attack", fight = "attack",
   use = "use", read = "read",
}
local filler = {                  -- little words ignored entirely
   the = true, a = true, an = true,
}
local prep = {                    -- prepositions that introduce a 2nd object
   with = true, using = true, at = true, to = true,
   on = true, onto = true, into = true, ["in"] = true,   -- "in" is a keyword, so quote it
   through = true, thru = true,                          -- "push X through window"
}

-- ---------------------------------------------------------------------------
-- 2. LOW-LEVEL HELPERS
-- ---------------------------------------------------------------------------
local function inputsplit(s, sep)
   sep = sep or "%s"
   local t = {}
   for word in string.gmatch(s, "([^" .. sep .. "]+)") do
      t[#t + 1] = word                       -- append idiom
   end
   return t
end

local function deepcopy(t)
   if type(t) ~= "table" then return t end
   local c = {}
   for k, v in pairs(t) do c[k] = deepcopy(v) end
   return c
end

local function merge(base, extra)            -- base overlaid with extra
   local out = {}
   for k, v in pairs(base) do out[k] = v end
   if extra then for k, v in pairs(extra) do out[k] = v end end
   return out
end

-- serialize pure DATA (strings/numbers/booleans/tables) to loadable Lua source.
-- never sees a function, because functions live in protos, not in state.
local function serialize(v)
   local t = type(v)
   if t == "string" then return string.format("%q", v)
   elseif t == "number" or t == "boolean" then return tostring(v)
   elseif t == "table" then
      local parts = {}
      for k, val in pairs(v) do
         parts[#parts + 1] = "[" .. serialize(k) .. "]=" .. serialize(val)
      end
      return "{" .. table.concat(parts, ",") .. "}"
   end
   error("cannot serialize a " .. t)
end

-- typed line -> { verb, noun, tool } or nil
local function cmd_parse(input)
   local words = inputsplit(input:lower())
   if #words == 0 then return nil end
   local first = words[1]

   if dir_canon[first] then
      return { verb = "go", noun = dir_canon[first] }
   end
   if move_verbs[first] then
      for i = 2, #words do
         if dir_canon[words[i]] then return { verb = "go", noun = dir_canon[words[i]] } end
      end
      return { verb = "go" }
   end

   local v = verb_canon[first]
   if v then
      local cmd = { verb = v }
      local i = 2
      while i <= #words do
         local w = words[i]
         if prep[w] then                       -- "with/at/to/on/into..." -> the 2nd object
            i = i + 1
            while i <= #words and filler[words[i]] do i = i + 1 end
            local obj = words[i]; i = i + 1
            -- the 2nd object can be a direction ("throw bread to the north") or an entity
            if obj and dir_canon[obj] then cmd.dir = dir_canon[obj] else cmd.tool = obj end
         elseif dir_canon[w] then              -- a bare direction ("throw bread north") is a target too
            cmd.dir = dir_canon[w]; i = i + 1
         elseif filler[w] then
            i = i + 1
         else
            if not cmd.noun then cmd.noun = w end
            i = i + 1
         end
      end
      -- a leading preposition ("talk to prisoner") means the prepositional
      -- object IS the thing acted on, not a separate target
      if not cmd.noun then cmd.noun = cmd.tool; cmd.tool = nil end
      return cmd
   end

   return nil
end

-- ---------------------------------------------------------------------------
-- 3. WORLD MODEL
-- ---------------------------------------------------------------------------
-- NOTE: `world` is never reassigned -- only its FIELDS are (world.entities, etc).
-- That is why the accessors below, which close over `world`, always see the
-- current game even after new_game()/load_game() swap the contents.
local protos = {}
local placements = {}
local world = {}
local running = true
local game_over = false           -- set on win/lose so run() holds the final screen
local SLOT = "ett.slot1"

local function E(id)  return world.entities[id] end     -- entity row by id
local function P(e)   return protos[e.proto] end        -- its prototype
local function here() return E("player").location end   -- current room id

local function text_of(e)
   local d = P(e).desc
   if type(d) == "function" then return d(e) else return d end
end

-- a short "seen from a distance" view of a room (e.g. through a window): the
-- author's `glimpse` text if set, otherwise just the first sentence of the
-- full description, so the view is always limited rather than the whole room.
local function glimpse_of(roomid)
   local r = E(roomid)
   if not r then return nil end
   local g = P(r).glimpse
   if g then return type(g) == "function" and g(r) or g end
   local full = text_of(r)
   return full:match("^[^.]*%.") or full          -- text up to (and incl.) the first period
end

local function contents(cid)
   local out = {}
   for id, e in pairs(world.entities) do
      if e.location == cid then out[#out + 1] = id end
   end
   return out
end

-- a carried item whose proto matches keyid, or nil. Lets locks be opened with
-- "unlock <thing>" (no "with <key>") as long as the right key is in hand.
local function held_key(keyid)
   for _, id in ipairs(contents("player")) do
      if E(id).proto == keyid then return E(id) end
   end
   return nil
end

local function reachable(id)
   local e = E(id)
   if not e then return false end
   local loc = e.location
   if loc == here() or loc == "player" then return true end
   local c = E(loc)
   if c and c.is_open and reachable(loc) then return true end
   return false
end

local function find(noun)
   if not noun then return nil end
   for id, e in pairs(world.entities) do
      if (P(e).name == noun or id == noun) and reachable(id) then return id end
   end
   return nil
end

local function run_dialog(npc)
   local tree = P(npc).dialog
   local nodeid = npc.dialog_node or "start"
   while true do
      local node = tree[nodeid]
      if not node then break end
      pc.print("")
      pc.print(P(npc).name .. ': "' .. node.text .. '"')
      if not node.options or #node.options == 0 then break end
      for i, opt in ipairs(node.options) do
         pc.print("  " .. i .. ") " .. opt.label)
      end
      local choice = tonumber(pc.input("> "))
      local opt = choice and node.options[choice]
      if not opt then
         pc.print("(type the number of a choice)")
      else
         if opt.effect then opt.effect(npc) end
         -- NOTE: the field is `next`, NOT `goto` -- `goto` is a reserved Lua keyword.
         if opt.next then nodeid = opt.next; npc.dialog_node = nodeid else break end
      end
   end
end

local function look_room()
   local room = E(here())
   pc.print("")
   pc.print(text_of(room))
   for _, id in ipairs(contents(here())) do
      if id ~= "player" then
         local e = E(id)
         pc.print("  There is a " .. P(e).name .. " here.")
         if e.is_open then
            for _, cid in ipairs(contents(id)) do
               pc.print("    Inside: a " .. P(E(cid)).name)
            end
         end
      end
   end
   local dirs = {}
   for d in pairs(room.exits) do dirs[#dirs + 1] = d end
   if #dirs > 0 then pc.print("Exits: " .. table.concat(dirs, ", ")) end
end

local function go(dir)
   if not dir then pc.print("Go where?"); sfx.play("error"); return end
   local room = E(here())
   local dest = room.exits[dir]
   if not dest then pc.print("You can't go " .. dir .. "."); sfx.play("error"); return end
   for _, id in ipairs(contents(here())) do
      if E(id).guarding == dir then
         pc.print("The " .. P(E(id)).name .. " blocks the way " .. dir .. ".")
         sfx.play("error")
         return
      end
   end
   E("player").location = dest
   look_room()
   if E(dest).win then
      pc.print("")
      pc.print("*** YOU ESCAPED THE TOWER ***")
      sfx.play("win")
      running = false; game_over = true
   elseif E(dest).lose then
      -- a fatal room: `lose` may be a custom death line, or just `true`
      pc.print("")
      pc.print(type(E(dest).lose) == "string" and E(dest).lose or "*** YOU DIED ***")
      sfx.play("lose")
      running = false; game_over = true
   else
      sfx.play("move")
   end
end

local function apply(cmd)
   if cmd.verb == "go" then go(cmd.noun); return end
   local id = find(cmd.noun)
   if not id then
      pc.print("You don't see any " .. (cmd.noun or "such thing") .. " here.")
      sfx.play("error")
      return
   end
   local e = E(id)

   -- resolve the indirect object (the "with/at/to" target), if any
   local other_id = cmd.tool and find(cmd.tool)
   local other = other_id and E(other_id) or nil

   -- the TARGET reacts first: e.g. "throw bread at prisoner" -> prisoner.react.throw
   if other then
      local react = P(other).react
      if react and react[cmd.verb] then
         react[cmd.verb](other, e, cmd)             -- self = target, other = item, cmd = full command
         sfx.play(sfx.for_verb(cmd.verb))            -- the action still happened
         return                                      -- the reaction fully handled it
      end
   end

   local handler = P(e).verbs[cmd.verb]
   if not handler then
      pc.print("You can't " .. cmd.verb .. " the " .. P(e).name .. ".")
      sfx.play("error")
      return
   end
   handler(e, other, cmd)                            -- handler(self, tool, cmd)
   sfx.play(sfx.for_verb(cmd.verb))
end

local function tick_all()
   for _, e in pairs(world.entities) do
      local t = P(e).tick
      if t then t(e) end
   end
end

local function new_game()
   world.entities = {}
   world.flags = {}
   for _, p in ipairs(placements) do
      local row = deepcopy(p.state)
      row.id = p.id
      row.proto = p.proto
      row.location = p.location
      world.entities[p.id] = row
   end
end

local function save_game()
   local data = "return {entities=" .. serialize(world.entities) ..
                ",flags=" .. serialize(world.flags) .. "}"
   return pc.save(SLOT, data)
end

local function load_game()
   local s = pc.load(SLOT)
   if not s then return false end
   local chunk = load(s)
   if not chunk then return false end
   local data = chunk()
   world.entities = data.entities
   world.flags = data.flags
   return true
end

-- ---------------------------------------------------------------------------
-- 4. AUTHORING HELPERS
-- ---------------------------------------------------------------------------
-- register() stores a prototype and records its single starting instance.
-- (Many-of-a-kind: register the proto once, then place several ids that set
--  proto = that id. Most narrative objects are unique, so 1:1 is simplest.)
local function register(id, proto, location, state)
   protos[id] = proto
   placements[#placements + 1] =
      { id = id, proto = id, location = location, state = state or {} }
end

local item_verbs = {
   look  = function(e) pc.print(text_of(e)) end,
   take  = function(e) e.location = "player"; pc.print("You take the " .. P(e).name .. ".") end,
   drop  = function(e) e.location = here();   pc.print("You drop the " .. P(e).name .. ".") end,
   -- throw lands the item at the TARGET's location: a direction -> the adjacent
   -- room; an entity -> wherever it is; nothing -> just at your feet.
   throw = function(e, target, cmd)
      local name = P(e).name
      if cmd and cmd.dir then
         local dest = E(here()).exits[cmd.dir]
         if dest then
            e.location = dest
            pc.print("You hurl the " .. name .. " " .. cmd.dir .. ".")
         else
            e.location = here()
            pc.print("There's no way " .. cmd.dir .. "; the " .. name .. " bounces back.")
         end
      elseif target then
         e.location = target.location
         pc.print("You throw the " .. name .. " at the " .. P(target).name .. ".")
      else
         e.location = here()
         pc.print("You toss the " .. name .. " aside.")
      end
   end,
}

-- build the standard "unlock <thing> [with key]" handler shared by doors,
-- windows and lockable containers. The key may be named explicitly or simply
-- carried (held_key); naming the wrong item still fails.
local function unlock_verb(keyid)
   return function(e, tool)
      if not e.locked then
         pc.print("It's already unlocked.")
         return
      end
      local key = tool or held_key(keyid)
      if key and key.proto == keyid then
         e.locked = false
         pc.print("The key turns. The lock clicks open.")
      else
         pc.print("You need the right key to unlock it.")
      end
   end
end

local function room(spec)
   register(spec.id,
      { name = spec.name or spec.id, desc = spec.desc, glimpse = spec.glimpse,
        verbs = spec.verbs or {}, react = spec.react },
      nil,
      { exits = spec.exits or {}, win = spec.win, lose = spec.lose })
end

local function item(spec)
   register(spec.id,
      { name = spec.name or spec.id, desc = spec.desc, verbs = merge(item_verbs, spec.verbs), react = spec.react },
      spec.location, spec.state or {})
end

local function container(spec)
   local keyid = spec.key or "key"           -- which item proto unlocks it (if locked)
   local verbs = merge({
      look = function(e) pc.print(text_of(e)) end,
      unlock = unlock_verb(keyid),           -- "unlock chest [with key]" -- key optional
      open = function(e)
         if e.locked then pc.print("It won't open -- it's locked."); return end
         if e.is_open then pc.print("It's already open."); return end
         e.is_open = true
         pc.print("You open the " .. P(e).name .. ".")
         local inside = contents(e.id)
         if #inside == 0 then
            pc.print("  It's empty.")
         else
            for _, cid in ipairs(inside) do pc.print("  Inside is a " .. P(E(cid)).name .. ".") end
         end
      end,
      close = function(e) e.is_open = false; pc.print("You close the " .. P(e).name .. ".") end,
   }, spec.verbs)
   register(spec.id, { name = spec.name or "container", desc = spec.desc, verbs = verbs, react = spec.react },
            spec.location, merge({ is_open = false, locked = spec.locked or false }, spec.state))
end

local function door(spec)
   local leads = spec.leads                  -- { dir =, to =, from = }
   local keyid = spec.key or "key"           -- which item proto unlocks it
   local verbs = {
      look = function(e) pc.print(text_of(e)) end,
      unlock = unlock_verb(keyid),           -- "unlock door [with key]" -- key optional
      open = function(e)
         if e.locked then
            pc.print("It won't budge -- it's locked.")
         elseif e.is_open then
            pc.print("It's already open.")
         else
            e.is_open = true
            E(leads.from).exits[leads.dir] = leads.to       -- the exit now exists
            pc.print("The " .. P(e).name .. " swings open, revealing the way " .. leads.dir .. ".")
         end
      end,
   }
   local desc = spec.desc or function(e)
      if e.is_open then return "An open doorway leads " .. leads.dir .. "."
      elseif e.locked then return "A heavy door blocks the way " .. leads.dir .. ", firmly locked."
      else return "A heavy door, unlocked but still shut." end
   end
   register(spec.id, { name = spec.name or "door", desc = desc, verbs = verbs, react = spec.react },
            spec.location, { locked = true, is_open = false })
end

local function window(spec)
   local leads = spec.leads                  -- { dir =, to =, from = }
   local keyid = spec.key or "key"           -- which item proto unlocks it
   -- `barred = true` makes THIS window permanent scenery: no key unlocks it and
   -- it never opens. Normal windows (barred omitted) keep the door-like behaviour.
   local barred = spec.barred
   -- the room you can see through the window. Defaults to wherever it leads, but
   -- can be set explicitly (e.g. a barred window with no exit still has a view).
   local overlooks = spec.overlooks or (leads and leads.to)
   local verbs = {
      look = function(e)
         pc.print(text_of(e))
         if overlooks and E(overlooks) then
            pc.print("Through it: " .. glimpse_of(overlooks))   -- windows let you see beyond
         end
      end,
      unlock = function(e, tool)             -- "unlock window [with key]" -- key optional
         if barred then
            pc.print("There's no lock -- just iron bars set fast in the stone.")
            return
         end
         unlock_verb(keyid)(e, tool)         -- same keyed/keyless logic as doors
      end,
      open = function(e)
         if barred then
            pc.print("The bars hold fast. The window won't open.")
         elseif e.locked then
            pc.print("It won't budge -- it's locked.")
         elseif e.is_open then
            pc.print("It's already open.")
         else
            e.is_open = true
            E(leads.from).exits[leads.dir] = leads.to       -- the exit now exists
            pc.print("The " .. P(e).name .. " swings open, revealing the way " .. leads.dir .. ".")
         end
      end,
   }
   local desc = spec.desc or function(e)
      if barred then return "A small window fitted with iron bars too narrow to pass." end
      if e.is_open then return "An open window leads " .. leads.dir .. "."
      elseif e.locked then return "A window blocks the way " .. leads.dir .. ", firmly locked."
      else return "A window, unlocked but still shut." end
   end
   register(spec.id, { name = spec.name or "window", desc = desc, verbs = verbs, react = spec.react },
            spec.location, { locked = true, is_open = false })
end

local function npc(spec)
   local verbs = merge({
      look = function(e) pc.print(text_of(e)) end,
      talk = function(e) run_dialog(e) end,
   }, spec.verbs)
   register(spec.id, { name = spec.name, desc = spec.desc, verbs = verbs, dialog = spec.dialog, react = spec.react },
            spec.location, { dialog_node = "start" })
end

local function enemy(spec)
   local verbs = merge({
      look   = function(e) pc.print(text_of(e)) end,
      attack = function(e) pc.print("The " .. P(e).name .. " is far too strong to fight head-on.") end,
   }, spec.verbs)
   register(spec.id, { name = spec.name, desc = spec.desc, verbs = verbs, tick = spec.tick, react = spec.react },
            spec.location, merge({ guarding = spec.guarding }, spec.state))
end

-- ---------------------------------------------------------------------------
-- 5. RUN  (called by main.lua after all content modules have registered)
-- ---------------------------------------------------------------------------
local function run()
   pc.cls()
   pc.print("=== ESCAPE THE TOWER ===")
   pc.print("Type 'help' for commands.")

   new_game()
   if pc.load(SLOT) then
      local ans = pc.input("Continue saved game? (y/n) "):lower()
      if ans == "y" or ans == "yes" then load_game(); pc.print("Loaded.") end
   end

   look_room()

   while running do
      local line = pc.input("> ")
      local lc = line:lower()
      if lc == "" then
         -- ignore
      elseif lc == "quit" or lc == "q" then
         running = false
      elseif lc == "save" then
         pc.print(save_game() and "Game saved." or "Save failed.")
      elseif lc == "load" then
         if load_game() then look_room() else pc.print("No save found.") end
      elseif lc == "look" or lc == "l" then
         look_room()
      elseif lc == "inventory" or lc == "inv" or lc == "i" then
         local inv = contents("player")
         pc.print("You are carrying:")
         if #inv == 0 then pc.print("  nothing")
         else for _, id in ipairs(inv) do pc.print("  " .. P(E(id)).name) end end
      elseif lc == "help" then
         pc.print("Move: north/south/east/west/up/down (or 'go up').")
         pc.print("Act:  look <x>, take <x>, drop <x>, throw <x>, open <x>,")
         pc.print("      unlock <x> with <y>, read <x>, eat <x>, talk to <x>.")
         pc.print("Meta: look, inventory, save, load, quit.")
      else
         local cmd = cmd_parse(line)
         if cmd then apply(cmd); tick_all() else pc.print("I don't understand that."); sfx.play("error") end
      end
   end

   -- the win/lose message is printed but never followed by another input;
   -- redraw it and wait for a key so the player can read the ending.
   if game_over and pc.flush then
      pc.flush()
      pc.getkey()
   end
end

-- ---------------------------------------------------------------------------
-- 6. EXPORTS  (what content modules and main.lua are allowed to touch)
-- ---------------------------------------------------------------------------
M.room      = room
M.item      = item
M.container = container
M.door      = door
M.window    = window
M.npc       = npc
M.enemy     = enemy
M.register  = register
M.run       = run

-- runtime accessors used inside content closures (ticks, dialog effects):
M.E        = E
M.P        = P
M.here     = here
M.contents = contents
M.flags    = function() return world.flags end   -- live table (call it each time)

return M
end
__modules["main"] = function()
-- ===========================================================================
-- main.lua -- entry point. Pull the engine, load every content module (in
-- order), then start the game. The require shim caches "engine", so all
-- content modules share the same engine instance and register into it.
-- ===========================================================================
local engine = require("engine")

require("content.floor1")
require("content.floor2")

-- wrap the raw display in the boxed view (top 2/3 = responses, bottom = input).
-- Must happen before run() so every pc.print/pc.input goes through the box.
require("screen").install()

engine.run()
end
__modules["screen"] = function()
-- ===========================================================================
-- screen.lua -- a boxed, buffered view over the raw pc display.
-- ===========================================================================
-- The game code keeps calling pc.print/pc.write exactly as before. This module
-- WRAPS those functions so that, instead of streaming straight down the screen,
-- output collects in a buffer and is drawn inside a box in the top 2/3 of the
-- screen. The bottom third holds a second box where the player types commands.
--
-- There is no scrolling: each new response clears the box and redraws. The
-- buffer is cleared lazily -- the first print of a NEW response wipes the old
-- one -- so pressing Enter on an empty line just redraws the current screen
-- rather than blanking it.
--
-- LUA REMINDER: we grab the ORIGINAL pc functions into locals first ("raw_*"),
-- then replace pc.print/pc.write/pc.input/pc.cls with our own. Our versions
-- call the raw ones to actually touch the hardware. Capturing them up front is
-- what lets us override the public names without losing the real behaviour.
-- ===========================================================================

local M = {}

-- the genuine display primitives, captured before we shadow the public names
local raw_cls   = pc.cls
local raw_print = pc.print
local raw_write = pc.write
local raw_input = pc.input
local raw_at    = pc.at
local raw_box   = pc.box

-- --- layout geometry (computed once from the real screen size) -------------
local COLS, ROWS = pc.size()                 -- 40 x 32 on the PicoCalc

-- response box: the top two-thirds
local RESP_X, RESP_Y = 1, 1
local RESP_W = COLS
local RESP_H = math.floor(ROWS * 2 / 3)      -- 21 rows (1..21)

-- a 2-cell margin between the text and the box border, all the way around
local MARGIN = 2
local TEXT_X = RESP_X + 1 + MARGIN           -- col 4
local TEXT_W = RESP_W - 2 * (1 + MARGIN)     -- 34 chars per line
local TEXT_Y = RESP_Y + 1 + MARGIN           -- row 4
local TEXT_H = RESP_H - 2 * (1 + MARGIN)     -- 15 text rows (4..18)

-- input box: a thin box near the top of the bottom third
local IN_X, IN_Y = 1, RESP_Y + RESP_H + 1    -- row 23 (one blank row below the response box)
local IN_W, IN_H = COLS, 3                    -- rows 23..25
local PROMPT_X = IN_X + 1 + MARGIN           -- col 4, lined up with the text
local PROMPT_Y = IN_Y + 1                     -- row 24, the box interior

-- --- output buffer ----------------------------------------------------------
local buffer = {}        -- list of already-wrapped display lines
local pending = nil      -- partial line built up by pc.write (no newline yet)
local fresh = true       -- true => the next print starts a brand new response

-- concatenate args the way the device's pc.print does: tostring, no separators
local function joined(...)
   local n = select("#", ...)
   local parts = {}
   for i = 1, n do parts[i] = tostring((select(i, ...))) end
   return table.concat(parts)
end

-- word-wrap one logical line (which may contain \n) to TEXT_W columns,
-- preserving any leading indentation on continuation lines.
local function wrap(text)
   local out = {}
   for raw in (text .. "\n"):gmatch("(.-)\n") do      -- split on explicit newlines
      raw = raw:gsub("\t", "   ")
      if raw == "" then
         out[#out + 1] = ""                            -- keep blank lines for spacing
      else
         local indent = raw:match("^(%s*)")
         local line = nil
         for word in raw:gmatch("%S+") do
            if line == nil then
               line = indent .. word
            elseif #line + 1 + #word <= TEXT_W then
               line = line .. " " .. word
            else
               out[#out + 1] = line
               line = indent .. word                   -- wrapped piece keeps the indent
            end
            while #line > TEXT_W do                     -- a single over-long word: hard-split
               out[#out + 1] = line:sub(1, TEXT_W)
               line = indent .. line:sub(TEXT_W + 1)
            end
         end
         out[#out + 1] = line
      end
   end
   return out
end

-- append a chunk of text to the buffer, clearing first if a new response began
local function append(text)
   if fresh then buffer = {}; pending = nil; fresh = false end
   if pending then text = pending .. text; pending = nil end
   for _, l in ipairs(wrap(text)) do buffer[#buffer + 1] = l end
end

-- draw the boxes and the buffered text (showing the last TEXT_H lines)
local function render()
   raw_cls()
   raw_box(RESP_X, RESP_Y, RESP_W, RESP_H)
   raw_box(IN_X, IN_Y, IN_W, IN_H)

   local n = #buffer
   local first = math.max(1, n - TEXT_H + 1)            -- only the newest lines fit
   local y = TEXT_Y
   for i = first, n do
      raw_at(TEXT_X, y)
      raw_write(buffer[i])
      y = y + 1
   end
end

-- --- the wrapped public API -------------------------------------------------

local function w_print(...)
   append(joined(...))           -- wrap() supplies the line break; don't add one here
end

local function w_write(...)
   if fresh then buffer = {}; pending = nil; fresh = false end
   pending = (pending or "") .. joined(...)
end

local function w_cls()
   buffer = {}; pending = nil; fresh = false
   raw_cls()
end

-- pc.input([prompt]) -- a passed prompt is shown as a line in the RESPONSE box
-- (it's part of the conversation); the caret is drawn in the input box. The
-- default "> " command prompt is treated as a plain caret, not response text.
local function w_input(prompt)
   if prompt and prompt ~= "" and prompt ~= "> " then
      append(tostring(prompt))
   end
   render()
   raw_at(PROMPT_X, PROMPT_Y)
   raw_write("> ")
   local line = raw_input()              -- read at the caret (device echoes here)
   fresh = true                          -- next print opens a fresh response
   return line
end

-- pc.flush() -- redraw the current buffer (for end-of-game messages that are
-- printed but never followed by another input). Returns true if it drew text.
local function w_flush()
   if #buffer == 0 then return false end
   render()
   return true
end

-- M.install() -- shadow the public pc functions with the boxed versions.
function M.install()
   pc.print = w_print
   pc.write = w_write
   pc.cls   = w_cls
   pc.input = w_input
   pc.flush = w_flush
end

return M
end
__modules["sound"] = function()
-- ===========================================================================
-- sound.lua -- short 2-3 tone "stingers" tied to player actions.
-- ===========================================================================
-- The device plays one blocking tone at a time via pc.tone(freq_hz, ms).
-- A stinger is just a little list of {freq, ms} notes we play back to back
-- (a freq of 0 is silence, handy for a gap). Each note BLOCKS until it ends,
-- so a stinger takes about the sum of its note durations -- keep them short.
--
-- LUA REMINDER: this file builds a table `M`, fills in a couple of functions,
-- and ends with `return M`. The build shim caches it, so every `require
-- ("sound")` hands back this same table.
-- ===========================================================================

local M = {}

-- name -> sequence of { frequency_hz, duration_ms } notes.
-- Frequencies are rough musical pitches (C5â‰ˆ523, G5â‰ˆ784, etc.); the exact
-- values matter less than the shape (rising = good, falling/low = bad).
local stingers = {
   move   = { { 392, 55 }, { 523, 55 } },                 -- two quick rising steps
   take   = { { 523, 40 }, { 659, 55 } },                 -- bright pickup blip
   drop   = { { 494, 40 }, { 330, 60 } },                 -- soft drop down
   open   = { { 523, 40 }, { 784, 90 } },                 -- unlock/open: bright success
   throw  = { { 784, 40 }, { 392, 70 } },                 -- whoosh downward
   talk   = { { 440, 40 }, { 554, 40 }, { 440, 45 } },    -- chatter
   attack = { { 147, 60 }, { 110, 90 } },                 -- low thud
   eat    = { { 330, 40 }, { 262, 70 } },                 -- gulp down
   error  = { { 220, 70 }, { 165, 120 } },                -- low descending buzz
   win    = { { 523, 90 }, { 659, 90 }, { 784, 200 } },   -- rising fanfare
   lose   = { { 392, 130 }, { 330, 130 }, { 196, 280 } }, -- falling dirge
   ok     = { { 523, 40 }, { 659, 50 } },                 -- generic confirm
}

-- canonical verb (from the engine's verb_canon) -> stinger name.
-- Anything not listed falls back to "ok" via M.for_verb below.
local verb_sound = {
   go = "move",
   take = "take", drop = "drop", throw = "throw",
   open = "open", close = "open", unlock = "open", lock = "open",
   talk = "talk", attack = "attack", eat = "eat",
   look = "ok", read = "ok", use = "ok",
}

-- M.play(name) -- play a stinger by name (unknown names play "ok").
function M.play(name)
   local seq = stingers[name] or stingers.ok
   for _, note in ipairs(seq) do
      pc.tone(note[1], note[2])           -- blocks until this note finishes
   end
end

-- M.for_verb(verb) -- map a canonical verb to its stinger name.
function M.for_verb(verb)
   return verb_sound[verb] or "ok"
end

return M
end
require("main")
