# build.ps1 -- bundle src/**/*.lua into a single game file.
#
# The PicoCalc engine runs one Lua file via dofile() and has no `require`
# (io/os/package are removed). So we author in modules under src/ and emit a
# single file that ships its own tiny `require` shim.
#
# A module's name is derived from its path under src/:
#   src/engine.lua          -> "engine"
#   src/content/floor1.lua  -> "content.floor1"
# Inside a module, `require("engine")` / `require("content.floor1")` works.
# main.lua is the entry point; the emitted file ends with require("main").
#
# Usage:  powershell -File build.ps1        (or:  pwsh build.ps1)

param(
   [string]$SrcDir = (Join-Path $PSScriptRoot 'src'),
   [string]$Out    = (Join-Path $PSScriptRoot 'games/escapethetower.lua')
)

$SrcFull = (Resolve-Path $SrcDir).Path
$files = Get-ChildItem -Path $SrcFull -Recurse -Filter *.lua | Sort-Object FullName

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('-- AUTOGENERATED by build.ps1 -- DO NOT EDIT. Edit files in src/ and rebuild.')
[void]$sb.AppendLine('local __modules, __loaded = {}, {}')
[void]$sb.AppendLine('local function require(name)')
[void]$sb.AppendLine('  if __loaded[name] == nil then __loaded[name] = __modules[name]() end')
[void]$sb.AppendLine('  return __loaded[name]')
[void]$sb.AppendLine('end')

foreach ($f in $files) {
   # path relative to src/, minus extension, separators -> dots
   $rel  = $f.FullName.Substring($SrcFull.Length).TrimStart('\', '/')
   $name = ($rel -replace '\.lua$', '') -replace '[\\/]', '.'
   $code = Get-Content -Raw -LiteralPath $f.FullName
   [void]$sb.AppendLine("__modules[`"$name`"] = function()")
   [void]$sb.Append($code)
   if (-not $code.EndsWith("`n")) { [void]$sb.AppendLine() }
   [void]$sb.AppendLine('end')
}

[void]$sb.AppendLine('require("main")')

# write UTF-8 with NO BOM (a BOM would corrupt the first line for the Lua parser)
[System.IO.File]::WriteAllText($Out, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Output "Built $Out from $($files.Count) module(s)."
